AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda function en Docker

Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: score_confianza.lambda_handler
      Runtime: python3.9
      CodeUri: lambda_function.zip
      MemorySize: 128
      Timeout: 10
